# Generated by Django 5.0.6 on 2024-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeRequirement',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
