# Generated by Django 5.0.6 on 2024-07-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.RecipeRequirement', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'TBSP'), ('tsp', 'TSP'), ('cup', 'CUP'), ('Kg', 'KG'), ('litres', 'LITRES'), ('ml', 'ML'), ('piece', 'PIECE'), ('g', 'G'), ('OT', 'OTHERS')], default='tbsp', max_length=10),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_requirements', to='inventory.menuitem'),
        ),
    ]
