# Generated by Django 5.0.6 on 2024-07-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_ingredients_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
